---
title: "Fremskrevet folkemengde"
output: html_document
date: '2022-08-18'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

```{r}
befprog <- read_delim("F:/Forskningsprosjekter/PDB 2455 - Helseprofiler og til_/PRODUKSJON/PRODUKTER/KUBER/KOMMUNEHELSA/KH2023NESSTAR/BEFPROG_2022-08-18-09-50.csv", delim = ";")
```


```{r}
k <- read_delim("85771.txt", delim = ";", locale=locale(encoding="latin1"))
f <- read_delim("85436.txt", delim = ";", locale=locale(encoding="latin1"))
n <- read_delim("85438.txt", delim = ";", locale=locale(encoding="latin1"))

folk <- rbind(n, f, k)
```
```{r}
folk %>% 
  separate(region, into = c("GEO", "Sted"), sep = " ", extra = "merge") %>% 
  mutate(GEO = as.integer(GEO)) %>% 
  filter(GEO > 99) %>% 
  count(alder)
```
```{r}
befprog %>% 
  filter(!is.na(TELLER)) %>% 
  mutate(GEO = as.integer(GEO)) %>% 
  filter(GEO > 99) %>% 
  count(ALDER)
```


```{r}
folk_kube <- folk %>% 
  separate(region, into = c("GEO", "Sted"), sep = " ", extra = "merge") %>% 
  separate(kjønn, into = c("KJONN", "kjønn"), sep = " ", extra = "merge") %>% 
  separate(alder, into = c("alder", "ALDER"), sep = " ", extra = "drop") %>% 
  mutate(ALDER = sub("-", "_", ALDER)) %>% 
  mutate(AAR = "2022_2022",
         PROGNOSEAAR = år,
         TELLER = `13600: Framskrevet folkemengde 1. januar, etter region, kjønn, alder, år og statistikkvariabel`,
         RATE = NA_real_,
         SMR = NA_real_,
         SPVFLAGG = 0) %>% 
  select(GEO, AAR, KJONN, ALDER, PROGNOSEAAR, TELLER, RATE, SMR, SPVFLAGG)

folk_kube
```

```{r}
befprog %>% 
  count(AAR)
```


```{r}
befprog %>% 
  filter(GEO == 0)
  arrange(GEO)
  
befprog %>% 
  count(ALDER) %>% 
  arrange(ALDER)
```
```{r}
folk %>% 
  separate(region, into = c("GEO", "Sted"), sep = " ", extra = "merge") %>% 
  separate(kjønn, into = c("KJONN", "kjønn"), sep = " ", extra = "merge") %>% 
  separate(alder, into = c("alder", "ALDER"), sep = " ", extra = "drop") %>% 
  mutate(ALDER = sub("-", "_", ALDER)) %>% 
  count(alder, ALDER)
```


```{r}
# read files
#kube1 <- read_delim(file1, delim = ";")
#kube2 <- read_delim(file2, delim = ";")

kube1 <- befprog
kube2 <- folk_kube %>% 
  mutate(KJONN = as.integer(KJONN))

# TEST EXPIRED COL
# in case om expired columns, cols in kube2 NOT in kube1
#kube1 <- kube1 %>% 
#  filter(SOES == 0) %>% 
#  select(-SOES)

# source compare kubes script
# needs to be in the current directory
# or specify path like this:
# source("path/to/where/script/is/compare_kubes_newcols.R")
source("compare_kubes_newdata.R")

# run find and write newdata
write_newdata()

# run merge and compare
compare <- compare_kube()

# write compare results table and provide summary, total and by year
view_write_compare(compare)
```

```{r}
compare %>% 
  filter(!is.na(TELLER.x),
         !is.na(TELLER.y)) %>% 
  mutate(GEO = as.integer(GEO)) %>% 
  filter(GEO > 99)

compare %>% 
  filter(!is.na(TELLER.x),
         !is.na(TELLER.y)) %>% 
  filter(KJONN== 2)
```
```{r}
befprog %>% 
  filter(ALDER == "0_4")
```
```{r}
folk_kube %>% 
  mutate(GEO = as.integer(GEO)) %>% 
  filter(GEO > 99) %>% 
  count(ALDER)
  filter(GEO > 99)
```
```{r}
befprog %>% 
  mutate(GEO = as.integer(GEO)) %>% 
  filter(GEO > 99) %>% 
  filter(!is.na(TELLER)) %>% 
  count(ALDER)
```

```{r}
befprog %>% 
  mutate(GEO = as.integer(GEO)) %>% 
  filter(GEO > 99) %>% 
 # filter(!is.na(TELLER)) %>% 
  filter(ALDER == "20_24")
```
```{r}
folk_kube %>% 
  mutate(GEO = as.integer(GEO)) %>% 
  #filter(GEO > 99) %>% 
  #filter(!is.na(TELLER)) %>% 
  filter(ALDER == "20_24")
```

